stages:
  - build
  - deploy

image: python:3.9
before_script:
  - pip install pipenv
  - pipenv install --system --deploy

platform:
  stage: build
  script:
    - aws cloudformation deploy deployment/custom-control-tower-buckets.cfn.yml
  only:
    refs:
      - master
    changes:
      - deployment/custom-control-tower-buckets.cfn.yml
  artifacts:
    paths:
      - deployment/

build:
  stage: build
  script:
    - bash deployment/substitute-vars.sh
    - cfn-lint
    - ./deployment/build-s3-dist.sh

deploy:
  stage: deploy
  only:
    - master
  script:
    - aws cloudformation deploy s3://custom-control-tower-templates/custom-control-tower-initiation.template # TODO finish command
