stages:
  - prepare
  - build
  - test
  - publish
  - deploy

image: $CI_REGISTRY_IMAGE/gitlab-ci:$CI_COMMIT_BRANCH
variables:
  SOLUTION_NAME: Ripe-Control-Tower-custom
  VERSION: $CI_COMMIT_SHORT_SHA
  TEMPLATE_BUCKET_NAME: solutions-reference
  DIST_BUCKET_NAME: custom-control-tower-dist

control-tower-customizations/gitlab-ci:
  stage: prepare
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE/gitlab-ci:$CI_COMMIT_BRANCH -f .gitlab/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/gitlab-ci:$CI_COMMIT_BRANCH
  only:
    changes:
      - .gitlab/Dockerfile
      -  Pipfile.lock

build:
  stage: build
  script:
    - ./deployment/build-s3-dist.sh $DIST_BUCKET_NAME $TEMPLATE_BUCKET_NAME $SOLUTION_NAME $VERSION
  artifacts:
    paths:
      - deployment/global-s3-assets
      - deployment/regional-s3-assets

lint:
  stage: test
  script:
    - cfn-lint

platform:
  stage: publish
  script:
    - |
      aws cloudformation deploy --no-fail-on-empty-changeset --stack-name custom-control-tower-deploy \
      --parameter-overrides DistBucketName=$DIST_BUCKET_NAME \
      --template-file deployment/custom-control-tower-deploy.cfn.yml --capabilities CAPABILITY_NAMED_IAM
    - aws s3 cp deployment/global-s3-assets s3://$DIST_BUCKET_NAME-$AWS_DEFAULT_REGION/$SOLUTION_NAME/$VERSION/ --recursive
    - aws s3 cp deployment/regional-s3-assets s3://$DIST_BUCKET_NAME-$AWS_DEFAULT_REGION/$SOLUTION_NAME/$VERSION/ --recursive
  only:
    - master

deploy:
  stage: deploy
  script:
    - |
      aws cloudformation deploy --no-fail-on-empty-changeset --stack-name custom-control-tower-initiation \
      --template-file deployment/global-s3-assets/custom-control-tower-initiation.template --capabilities CAPABILITY_NAMED_IAM \
      --parameter-overrides "PipelineApprovalEmail=''" "CodePipelineSource=AWS CodeCommit" \
      --s3-bucket $DIST_BUCKET_NAME-$AWS_DEFAULT_REGION
  only:
    - master
