stages:
  - test
  - build
  - deploy

image: python:3.9
variables:
  PIPENV_CACHE_DIR: $CI_BUILDS_DIR/venv
before_script:
  - pip install pipenv
  - pipenv install --system --ignore-pipfile --dev
cache:
  key:
    files:
      - Pipfile.lock
  paths:
    - venv/

lint:
  stage: test
  script:
    - bash deployment/substitute-vars.sh
    - cfn-lint

platform:
  stage: build
  script:
    - aws cloudformation deploy deployment/custom-control-tower-buckets.cfn.yml
  only:
    refs:
      - master
    changes:
      - deployment/custom-control-tower-buckets.cfn.yml
  artifacts:
    paths:
      - deployment/

build:
  stage: build
  script:
    - bash deployment/substitute-vars.sh
    - ./deployment/build-s3-dist.sh

deploy:
  stage: deploy
  only:
    - master
  script:
    - aws cloudformation deploy s3://custom-control-tower-templates/custom-control-tower-initiation.template # TODO finish command
