stages:
  - test
  - build
  - deploy

image: python:3.9
variables:
  PIPENV_CACHE_DIR: $CI_PROJECT_DIR/.cache
  SOLUTION_NAME: Ripe Control Tower custom
  VERSION: $CI_COMMIT_SHORT_SHA
  TEMPLATE_BUCKET_NAME: custom-control-tower-templates
  DIST_BUCKET_NAME: custom-control-tower-dist
before_script:
  - pip install pipenv
  - pipenv install --system --ignore-pipfile --dev
  - echo $PIPENV_CACHE_DIR
cache:
  key:
    files:
      - Pipfile.lock
  paths:
    - .cache

lint:
  stage: test
  script:
    - bash deployment/substitute-vars.sh
    - cfn-lint

platform:
  stage: build
  script:
    - ./deployment/substitute-vars.sh
    - aws cloudformation deploy deployment/custom-control-tower-buckets.cfn.yml
  only:
    refs:
      - master
    changes:
      - deployment/custom-control-tower-buckets.cfn.yml

build:
  stage: build
  script:
    - ./deployment/substitute-vars.sh
    - ./deployment/build-s3-dist.sh $DIST_BUCKET_NAME $TEMPLATE_BUCKET_NAME $SOLUTION_NAME $VERSION
  artifacts:
    paths:
      - deployment/

deploy:
  stage: deploy
  only:
    - master
  script:
    - aws cloudformation deploy s3://custom-control-tower-templates/custom-control-tower-initiation.template # TODO finish command
